name: AppBuilder Mac

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Release tag"
        required: true
        default: "v1.0.0"
        type: string

jobs:
  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [20.11.1] # Specify your Node.js version
        rust-version: [1.76.0] # Specify your Rust version
        architecture: [x86_64, aarch64] # Specify both Intel and Apple Silicon architectures

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Rust ${{ matrix.rust-version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
          override: true

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install libvips
        run: brew install vips

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Rebuild sharp
        run: pnpm rebuild sharp

      - name: Build Next.js app
        run: pnpm build

      - name: Set architecture for Tauri build
        run: echo "ARCH=${{ matrix.architecture }}" >> $GITHUB_ENV

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          args: ${{ matrix.architecture }}-apple-darwin
          tagName: ${{ github.ref_name }}
          releaseName: "v__VERSION__"
          releaseBody: |
            See the assets to download this version and install.
          releaseDraft: true
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tauri-build-macos-${{ matrix.architecture }}
          path: src-tauri/target/release/bundle/macos/
