name: App Builder

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Release tag"
        required: true
        default: "v1.0.0"
        type: string

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        include:
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: 20.x.x

      - name: Install Rust (Stable)
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Install app dependencies and build web
        run: pnpm install --frozen-lockfile

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.event.inputs.releaseTag || github.ref_name }}
          releaseName: "[Unaffiliated] Google Keep v${{ github.event.inputs.releaseTag || github.ref_name }}"
          releaseDraft: true
          prerelease: false

      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets
          asset_path: D:\a\SouffleAppTauri\SouffleAppTauri\src-tauri\target\release\bundle\msi\Windmill_1.0.2_x64_en-US.msi
          asset_name: artifact.msi
          asset_content_type: application/octet-stream
