name: Build and Release

on:
  push:
    branches:
      - release # ou le nom de la branche que vous souhaitez utiliser pour déclencher la construction

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Utilisez la version de Node.js recommandée pour votre projet

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build # Assurez-vous que ce script existe dans votre package.json

      - name: Create release directory
        run: mkdir -p./release

      - name: Copy built files to release directory
        run: cp -r dist/*./release/ # Modifiez 'dist/*' par le chemin vers vos fichiers de release si nécessaire

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Add release files" -m "Automated by GitHub Actions"
          git push
